Ruheej1-Project Addtion-The Drum Kit
LetsGrowMoreCommunity/WebDev-Playyard pull request #73
Opened 2021-08-06 19:37 UTC by Ruheej1

# Description
Adding the project "The Drum Kit" using HTML,CSS and JavaScript, It is a fun interactive and simple project that lets user play drum sounds on mouseclick or keypress.

Fixes #64  

## Type of change

- [x] New Project / Docs 
- [x] This change requires a documentation update

# Explain the Testing instructions

**Test Configuration**:
* Operating system: Windows 
* Version:10
* Text-editors used: Atom
 
# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
# ATTACH SCREEN-SHOTS / DEPLOYMENT LINK 
https://ruheej1.github.io/WebDev-Playyard/Projects/The%20Drum%20Kit/

![Untitled (2)](https://user-images.githubusercontent.com/59756474/128562869-bb2fa9c8-e772-4666-a9b9-002737e13c64.png)

2021-08-07 14:52 UTC, rohan-kulkarni-25 commented
@Sanskriti2401 @SnehaAgarwal361  Have a look and please give a review

2021-08-07 17:15 UTC, Sanskriti2401 requested changes
@Ruheej1 
1. Move all images inside media folder (you have included in css files)
2. Update your Readme. Write about your project or steps to set up and include your deployment link in it.

2021-08-08 06:44 UTC, Ruheej1 commented
I have made the required changes, please check
Fixes #73

2021-08-09 11:44 UTC, Sanskriti2401 approved these changes

2021-08-09 11:44 UTC, merged